"""changing type of sent by me and adding ack timestamp

Revision ID: 24f5314feb00
Revises: 641dab2d4e18
Create Date: 2026-03-04 13:33:40.698705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f5314feb00'
down_revision: Union[str, Sequence[str], None] = '641dab2d4e18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('ack_timestamp', sa.DateTime(), nullable=True))
    op.alter_column('messages', 'sent_by_me',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='sent_by_me::boolean')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sent_by_me',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               postgresql_using='sent_by_me::integer')
    op.drop_column('messages', 'ack_timestamp')
    # ### end Alembic commands ###
