"""adding message table

Revision ID: 8c1ec59c47b7
Revises: e37dc3140725
Create Date: 2026-03-04 13:27:42.785212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1ec59c47b7'
down_revision: Union[str, Sequence[str], None] = 'e37dc3140725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.LargeBinary(length=4), nullable=True),
    sa.Column('destination_id', sa.LargeBinary(length=4), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('rssi', sa.Float(), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('converstation', sa.String(), nullable=True),
    sa.Column('sent_by_me', sa.Integer(), nullable=True),
    sa.Column('ack_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
