"""added tables: nodes, routes

Revision ID: 9e3bae2377ae
Revises: e0a581fdd1d8
Create Date: 2026-02-26 18:03:30.668248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3bae2377ae'
down_revision: Union[str, Sequence[str], None] = 'e0a581fdd1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.LargeBinary(length=4), nullable=False),
    sa.Column('gps_coordinates', sa.String(), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_id'), 'nodes', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('source', sa.LargeBinary(length=4), nullable=True),
    sa.Column('destination', sa.LargeBinary(length=4), nullable=True),
    sa.Column('next_hop', sa.LargeBinary(length=1), nullable=True),
    sa.Column('expiring_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['destination'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['source'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('sequence_number')
    )
    op.create_index(op.f('ix_routes_sequence_number'), 'routes', ['sequence_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_sequence_number'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_nodes_id'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
