"""create combined primary key for message

Revision ID: a4cd6c47ce76
Revises: 24f5314feb00
Create Date: 2026-03-04 14:35:01.040739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4cd6c47ce76'
down_revision: Union[str, Sequence[str], None] = '24f5314feb00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'source_id',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'source_id',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
