"""link_quality_entries_added

Revision ID: ad49cd77f1fd
Revises: 3532c3efd9f3
Create Date: 2026-04-08 19:12:44.509673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad49cd77f1fd'
down_revision: Union[str, Sequence[str], None] = '3532c3efd9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter', sa.LargeBinary(length=4), nullable=False),
    sa.Column('relay_node1', sa.LargeBinary(length=4), nullable=True),
    sa.Column('relay_node2', sa.LargeBinary(length=4), nullable=True),
    sa.Column('relay_node3', sa.LargeBinary(length=4), nullable=True),
    sa.Column('relay_node1_rxgood', sa.Integer(), nullable=True),
    sa.Column('relay_node1_rxbad', sa.Integer(), nullable=True),
    sa.Column('relay_node2_rxgood', sa.Integer(), nullable=True),
    sa.Column('relay_node2_rxbad', sa.Integer(), nullable=True),
    sa.Column('relay_node3_rxgood', sa.Integer(), nullable=True),
    sa.Column('relay_node3_rxbad', sa.Integer(), nullable=True),
    sa.Column('channel_util', sa.Float(), nullable=True),
    sa.Column('air_util_tx', sa.Float(), nullable=True),
    sa.Column('last_heard', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reporter'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_quality_id'), 'link_quality', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_quality_id'), table_name='link_quality')
    op.drop_table('link_quality')
    # ### end Alembic commands ###
