"""adding columns to the nodes table according to the node db in firmware

Revision ID: e37dc3140725
Revises: f10e86a051a6
Create Date: 2026-03-03 22:21:27.296274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37dc3140725'
down_revision: Union[str, Sequence[str], None] = 'f10e86a051a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('long_name', sa.String(), nullable=True))
    op.add_column('nodes', sa.Column('hw_model', sa.String(), nullable=True))
    op.add_column('nodes', sa.Column('public_key', sa.String(), nullable=True))
    op.add_column('nodes', sa.Column('snr', sa.Float(), nullable=True))
    op.add_column('nodes', sa.Column('hops_away', sa.Integer(), nullable=True))
    op.add_column('nodes', sa.Column('role', sa.String(), nullable=True))
    # Drop and recreate last_byte column with correct type
    op.drop_column('nodes', 'last_byte')
    op.add_column('nodes', sa.Column('last_byte', sa.LargeBinary(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate last_byte as INTEGER
    op.drop_column('nodes', 'last_byte')
    op.add_column('nodes', sa.Column('last_byte', sa.INTEGER(), nullable=True))
    op.drop_column('nodes', 'role')
    op.drop_column('nodes', 'hops_away')
    op.drop_column('nodes', 'snr')
    op.drop_column('nodes', 'public_key')
    op.drop_column('nodes', 'hw_model')
    op.drop_column('nodes', 'long_name')
    # ### end Alembic commands ###
