"""adding last byte to the node database

Revision ID: f10e86a051a6
Revises: 9e3bae2377ae
Create Date: 2026-03-03 14:22:56.790913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10e86a051a6'
down_revision: Union[str, Sequence[str], None] = '9e3bae2377ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('last_byte', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'last_byte')
    # ### end Alembic commands ###
