"""fix conversation column typo

Revision ID: f6c5eb6cd137
Revises: 181979549f4f
Create Date: 2026-03-04 15:14:52.721803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c5eb6cd137'
down_revision: Union[str, Sequence[str], None] = '181979549f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename column to preserve data instead of dropping and adding
    op.alter_column('messages', 'converstation', new_column_name='conversation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename back
    op.alter_column('messages', 'conversation', new_column_name='converstation')
    # ### end Alembic commands ###
